version: '3.8'

services:
  kafka:
    image: confluentinc/cp-kafka:7.8.3
    container_name: kafka

    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 9092 || exit 1" ]
      interval: 5s
      timeout: 15s
      retries: 10
      start_period: 20s

    ports:
      - "9092:9092"

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_KRAFT_MODE: 'true'
      CLUSTER_ID: '1L6g7nGhU-eAKfL--X25wo'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data

    volumes:
      - kafka_kraft:/var/lib/kafka/data


  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - ${KAFKA_UI_PORTS}:8080

    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

    depends_on:
      kafka:
        condition: service_healthy


  mongodb:
    image: docker.io/library/mongo:7.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}

    volumes:
      - mongo_data:/data/db



  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.3.0
    container_name: elasticsearch
    ports:
      - "9200:9200"

    healthcheck:
      test: [ "CMD-SHELL",
              "curl -s -u http://elasticsearch:9200/_cluster/health 
              | grep -q '\\\"status\\\":\\\"green\\\"\\|\\\"status\\\":\\\"yellow\\\"'" ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 60s

    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m

    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data


  kibana:
    image: docker.elastic.co/kibana/kibana-wolfi:9.3.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy




  metadata_service:
    build:
      context: metadata_service

    environment:
      KAFKA_URL: "kafka:9092"
      KAFKA_TOPIC: "audio_file_metadata"

      ELASTIC_URL: 'http://elasticsearch:9200'

      podcasts_folder: "../audio"

    volumes:
      - ${local_podcasts_folder}:/audio


  uuid_service:
    build:
      context: uuid_consumer

    environment:
      KAFKA_URL: 'kafka:9092'
      KAFKA_TOPIC: 'audio_file_metadata'

      MONGO_URL: 'mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/?authSource=admin'
      MONGO_DATABASE: 'audio_files'

      ELASTIC_URL: 'http://elasticsearch:9200'
      ELASTIC_INDEX: 'audio_files_data'

    volumes:
      - ${local_podcasts_folder}:/audio



volumes:
  kafka_kraft:
  mongo_data:
  elasticsearch-data:

